### ISSUE TITLE
Fill in ReadMe file with appropriate links

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4se9#1]
I have created a model in airtable with slug: smiles-iupac, the rest of the information needs to be filled in in the README file and I'll add it to the airtable

**Comment by carcablop** [comment]
Hi @GemmaTuron 
The readme is already updated.
Link to last commit. https://github.com/ersilia-os/eos4se9/commit/3390dbc463b9f06573492424033087301ec21c55

**Comment by GemmaTuron** [comment]
Hi @carcablop 
I have edited the slug: it can only have one slug per model, and as short as possible, as it is equivalent to the model identifier (you can fetch models through the CLI with the slug). We are improving the way we fill in these readme files, automatizing them but for the moment we still need manual revision.
Can you also clarify why did you choose Retrained model? I thought the weights were already provided and you did not have to retrain anything (it would be then pretrained)

**Comment by carcablop** [comment]
Hi. @GemmaTuron. 
I will correct it. It's my mistake, I don't have to retrain anything. It is pre-trained. Thank you.

**Comment by carcablop** [comment]
@GemmaTuron  I have seen that the slug is not visible in the template, although when I edit it, I do see the slug, I think it is because it is inside "< >".
