### ISSUE TITLE
Test model eos4se9 in CLI and Colab

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4se9#2]

**Comment by DhanshreeA** [comment]
I have tested the model and it works both on CLI and Colab. 

CLI output: 
[eos4se9_output.csv](https://github.com/ersilia-os/eos4se9/files/10446487/eos4se9_output.csv)

Colab link: :https://colab.research.google.com/drive/1yP5nysGx2OLPwjzxSeJHi-3TOAOBHpME?usp=sharing

**Comment by GemmaTuron** [comment]
Hi @karthikjetty 

Please provide an update on testing this model

**Comment by karthikjetty** [comment]
Model worked on my CLI (log attached below).
[eos4se9.log](https://github.com/ersilia-os/eos4se9/files/10484850/eos4se9.log).

Also ran successfully on Colab! https://colab.research.google.com/drive/1GOGIFy1bL-r3jMH-2dJwW-Vhq69WT3GK#scrollTo=TYmcRRZ4mnkx

**Comment by GemmaTuron** [comment]
Thanks, we can consider this completed then!
